public enum vip_type
{
    BUY_TILI_COUNT = 0,                 // 体力购买次数
    BUY_EXP_STAGE_COUNT = 1,                 // 经验副本购买次数
    REFRESH_MSHOP_COUNT = 2,                 // 神秘商店刷新次数
    USE_TILI_S_COUNT = 3,                 // 体力丹（小）
    USE_TILI_M_COUNT = 4,                 // 体力丹（中）
    USE_TILI_L_COUNT = 5,                 // 体力丹（大）
    BUY_PK_STAGE_COUNT = 6,                 // 比武场购买次数
    TILI_RESTORE_TIME = 7,                 // 体力恢复减少（单位：秒）
    LEAVE_EXP_MUL = 8,                 // 离线经验倍数
    PLOT_STAGE_RESET = 9,                 // 剧情副本重置次数
    MASTER_STAGE_RESET = 10,                 // 精英副本重置次数
    ONE_KEY_CLEAN = 11,                 // 一键扫荡
    MSHOP_SELL_ZONE = 12,                 // 神秘商店栏位增加
    BATTLE_HERO_COUNT = 13,                 // 英雄上阵数量
    LUCKDRAW_SALE_OFF = 14,                 // 抽奖折扣（%）
};

public enum game_err_code
{
    RES_OK              = 1,

    NULL                = -1,

    CONFIG_ERR          = -101,                 // 服务器配置错误
    INTERNAL_ERR        = -102,                 // 服务器内部错误
    PARAMETER_ERR       = -103,                 // 参数错误
    NOT_LOGIN           = -104,                 // 未登录
    DATA_ERR            = -105,                 // 数据错误
    MAX_OL_TM_REACHED   = -106,                 // 已达到最大反沉迷累积在线时间
    INCORRECT_CHAR      = -107,                 // 非法字符
    CHAR_SEALED         = -108,                 // 被封号了

    CANT_DEL_SCODE_ERR  = -149,                 //安全密码错误
    CHA_CARR_CNT_REQUIRE= -150,                 // 没有达到创建该职业所需条件
    CHA_SEX_ERR         = -151,                 // 角色性别错误
    CARR_NOT_EXIST      = -152,                 // 职业不存在
    SAME_CHA_NAME_EXIST = -153,                 // 已存在同名角色
    MAX_CHA_REACHED     = -154,                 // 角色已达上限，不能再创建角色了
    CANT_DEL_CLANP_CHA  = -155,                 // 不能删除帮主角色
    FUNCTIONAL_TEMP_SHUTDOWN = -156,            // 功能临时关闭，请耐心等待并注意官方公告
    CANT_DEL_CHA_3_DAY  = -157,                 // 角色创建后3天之内不能删除
    CHAR_NOT_EXIST      = -158,                 //角色不存在

    LOGIN_BY_OTHER      = -161,                 // 同一用户已经从其他地方登录
    ALREADY_LOGIN       = -162,                 // 已经登录过了
    SESSION_LOIN_NEED_LOGOUT_FIRST  = -163,     // 同一会话已登录其他用户，需要先退出再重新登录
    USER_NOT_EXIST      = -164,                 // 用户不存在
    LOGIN_VALIDATE_ERR  = -165,                 // 登录验证失效，需重新登录
    CHARACTER_NOT_EXIST = -166,                 // 角色不存在或者已离线
    CHARACTER_NOT_NEARBY= -167,                 // 角色不在附近
    CHARACTER_NOT_IN_SAME_MAP       = -168,     // 角色与自己不在同一地图
    WRONG_CHARACTER_ID  = -169,                 // 不存在这个角色
    SHOUT_TOO_FREQUENT  = -170,                 // 发言过于频繁
    NO_OLAWD_LEFT       = -171,                 // 没有在线奖励可以领取了
    OLAWD_TIME_LEFT     = -172,                 // 还没到可以领取奖励的时间
    SORT_PKG_TO_FREQUENT= -173,                 // 整理背包过于频繁
    ITM_CARD_ID_ERR     = -174,                 // 道具卡id错误
    ITM_CARD_FETCHED    = -175,                 // 该道具卡已领取过
    ITM_CARD_TP_ERROR   = -176,                 // 不存在的道具卡类型
    ITM_CARD_EXPIRE     = -177,                 // 道具卡已过期
    FORB_TALK           = -178,                 // 被禁言了
    YOU_ARE_DEAD        = -179,                 // 你已经死亡，不能完成该操作
    SERVER_IS_CLOSING   = -180,                 // 服务器即将关闭
    ITM_CARD_UID_WRONG  = -181,                 // 不是本用户的道具卡
    ITM_CARD_CID_WRONG  = -182,                 // 不是本角色的道具卡
    OLTMA_TM_NOT_ENOUGH = -183,                 // 领取奖励在线时间不足
    OLTMA_ALREADY_GET   = -184,                 // 已经领取过在线时间奖励
    YOU_ARE_GHOST       = -185,                 // 灵魂状态不能完成该操作
    CHANG_LINE_TOO_BUSY = -186,                 // 你换线过于频繁
    CHAT_LVL_ERR                = -187,         // 等级不足，不能发言
    CHANG_LINE_MAP_LIMIT        = -188,         // 此地图不能换线

    ATTACK_NOT_EXSIT        = -190,         // 目标不在此地图

    /// <summary>
    /// 无法攻击
    /// </summary>
    CANT_ATK=-200,

    MP_NOT_ENOUGH               = -201,         // 法力不足
    HP_NOT_ENOUGH               = -202,         // 生命不足
    AGRY_NOT_ENOUGH             = -203,         // 怒气不足
    ACT_NOT_ENOUGH              = -204,         // 行动力不足
    CANT_ATK_PL_IN_PEACE        = -205,         // 和平状态不能攻击其他玩家
    CANT_PK_IN_PEACE_MAP        = -206,         // 和平地图中不能pk
    CANT_PK_IN_PEACE_ZONE       = -207,         // 和平区域中不能pk
    CANT_RESPAWN_LIVE_CHA       = -208,         // 不能复活未死亡角色
    NOT_RESPAWN_ITEM            = -209,         // 不是复活道具
    PK_V_NOT_NEED_CHANGE        = -210,         // PK状态一样，无需修改
    PK_V_ALREADY_WHITE          = -211,         // 罪恶值已经为0
    CANT_SET_PEACE_WITH_FLOWKA  = -212,         // 运镖任务中不能改为和平模式
    PK_SET_PEACE_TM_NOT_REACH   = -213,         // 开启战斗模式后XX时间内才能切换回和平模式
    CANT_RESPAWN_YET            = -214,         // 复活等待时间未到，还不能复活
    CANT_IMMRESPAWN             = -215,         // 本副本中不能原地复活
    RECALLEXP_NO_EXP            = -216,         // 没有补偿经验可领取
    RECALLEXP_ALREADY_GET       = -217,         // 今天已经领取过该补偿经验
    MAX_CARRLVL_REACHED         = -218,         // 已达到最大职业等级
    ATTPT_NOT_ENOUGH            = -219,         // 可用属性点不足
    ATTPT_CANNT_RESET           = -220,         // 没有可洗的点
    MAX_RESETLVL_REACHED        = -221,         // 已达到最大转生等级
    RESETLVL_CNT_NOT_ENOUGH     = -222,         // 转生次数已经用完
    TODAY_BUY_ACT_V_NOT_ENOUGH  = -223,         // 今天的购买次数已经用完
    CANT_ATTACK_SELF_PET        = -224,         // 不能攻击自己的宠物
    ALREAY_FULL_LEVEL           = -225,         //  已达到最高等级
    MAP_CANT_IMMRESPAWN         = -226,         // 本地图中不能原地复活
    VIP_LVL_LISS_THAN_THREE     = -227,         // VIP等级小于三级

    COLLECT_TARGET_NOT_EXIST    = -250,         // 采集目标不存在
    COLLECT_TARGET_DIE          = -251,         // 采集目标尚未恢复
    NOT_COLLECT_TARGET          = -252,         // 不是采集目标
    COLLECT_TARGET_NOT_NEARBY   = -253,         // 采集目标不在范围内

    MAIL_NO_ITEM                = -300,         // 邮件没有附件
    CANT_MAIL_SELF              = -301,         // 不能给自己发邮件
    FGUESS_NOT_FINISH           = -302,         // 有尚未完成的划拳
    FGUESS_NOT_START            = -303,         // 尚未开始划拳
    NOT_ENOUGH_FGUESS_PT        = -304,         // 划拳兑换币不足
    CGAME_NO_CARD_AWD           = -305,         // 没有翻牌奖励
    CGAME_NOT_GETAWD            = -306,         // 你今天的领奖次数已经用完了
    CGAME_NOT_OPEN_CARD         = -307,         // 还未开启此牌
    CGAME_CARD_TOO_LITTLE       = -308,         // 你拥有的牌太少，不能使用此功能
    MAIL_HAS_ITEM               = -309,         // 邮件中包含附件

    GMIS_NOT_OPEN               = -350,         // 目标任务未开启
    GMIS_EXPIRED                = -351,         // 目标任务已过期
    GMIS_AWD_ALREADY_GET        = -352,         // 目标任务奖励已获取

    DMIS_ALREADY_FINISH         = -370,         // 该每日必做任务已经完成了
    DMIS_CANT_YB_FIN            = -371,         // 该每日必做任务无法立即完成
    DMIS_AWD_ALREADY_GET        = -372,         // 每日必做任务奖励已经获取过了
    DMIS_NONE_FIN               = -373,         // 尚未完成任何每日必做任务
    DMIS_CANT_ADD_STATE         = -374,         // 目标不能再添加该状态了
    DMIS_NOT_FIN                = -375,         // 每日任务尚未完成
    DMIS_SAWD_ALREADY_GET       = -376,         // 已获取过该每日任务奖励

    LEVEL_CREATE_MAP_ERROR      = -401,         // 创建副本地图出错
    LEVEL_YOU_NOT_IN_LEVEL      = -402,         // 你不在副本中
    LEVEL_YOU_NOT_IN_TEAM       = -403,         // 你不在队伍中，无法创建、加入队伍副本
    LEVEL_CREATE_ERROR          = -404,         // 创建副本失败
    LEVEL_CREATE_NO_BORN_MAP    = -405,         // 创建的副本没有出身地图
    LEVEL_MAP_NOT_IN_LEVEL      = -406,         // 当前副本中没有这幅地图
    LEVEL_ALREADY_CREATED       = -407,         // 该副本已经创建过了
    LEVEL_PREMIS_REQUIRE        = -408,         // 进入副本需要完成前置任务
    LEVEL_ITEM_REQUIRE          = -409,         // 缺少进入副本需要的道具
    LEVEL_ENTRY_CNT_REACHED     = -410,         // 已经达到进入副本的次数上限，不能再进入了
    LEVEL_TM_NOT_REACHED        = -411,         // 副本开启时间还未到
    LEVEL_TM_FINISHED           = -412,         // 副本时间已过
    LEVEL_TOO_DIFFICULT         = -413,         // 创建的副本难度过高
    LEVEL_NO_PRIZE              = -414,         // 你已经领取过该副本奖励或者该副本没有奖励
    LEVEL_ACCEPT_MIS_REQUIRE    = -415,         // 进入副本需要已接受某个任务
    LEVEL_CANT_CHECK_IN         = -416,         // 副本不能报名方式加入
    LEVEL_MAX_PLAYER_REACHED    = -417,         // 副本已达到最大玩家数
    LEVEL_CLAN_NOT_CHECKIN      = -418,         // 你的帮派未签入该副本
    LEVEL_ALREADY_IN_LEVEL      = -419,         // 已经在副本中了，需先退出副本
    LEVEL_NOT_FIN_ANY_LVL       = -420,         // 尚未完成任何副本
    LEVEL_NOT_FIN_SUCH_LVL      = -421,         // 该副本未完成
    LEVEL_DIFF_LVL_NOT_FIN      = -422,         // 该副本指定难度未完成
    LEVEL_FCNT_NOT_ENOUGH       = -423,         // 该副本完成次数不足
    LEVEL_BEST_TIME_REQUIRE     = -424,         // 该副本最佳通关时间过长
    LEVEL_LVL_IS_FINISH         = -425,         // 副本已结束，等待2分钟关闭中，不能进入
    LEVEL_CANT_ENTER_WITH_MISBUF= -426,         // 当前已接属性加成任务（如护送任务），不能进入副本
    LEVEL_CANT_CREATE_BY_USER   = -427,         // 副本不能直接创建
    LEVEL_ONLY_MATCH_ENTER      = -428,         // 副本只能通过匹配方式进入
    LEVEL_CLAN_ENTER            = -429,         // 副本只能通过帮派进入
    LEVEL_CANT_ENTER_WITH_ACHECK= -430,         // 当前已经在竞技场排队等待中，不能进入副本
    LEVEL_CARRC_LVL_PLY_FULL    = -431,         // 首席大弟子比赛人数已满
    LEVEL_NO_CARRC_AWD          = -432,         // 没有首席大弟子奖励
    LEVEL_CARRC_AWD_EXPIRE      = -433,         // 领取首席大弟子奖励超时
    LEVEL_CARRC_LVL_FINISH      = -434,         // 本轮首席大弟子已结束
    LEVEL_ENTER_CD_NOT_REACH    = -435,         // 进入副本的冷却时间未到，不能进入
    LEVEL_NEED_TEAM_LEADER_CRT  = -436,         // 只有队长才能创建队伍副本
    LEVEL_CANT_YB_FIN           = -437,         // 该副本无法立即通关
    LEVEL_YBFIN_COMBPT_REQUIRE  = -438,         // 立即通关副本战斗力不足
    LEVEL_YB_FIN_NOT_COMPLETE   = -439,         // 尚未通关的副本或副本难度层级不能立即通关
    LEVEL_NOT_YOUR_CLAN_TER     = -440,         // 不是你所在帮派的领地
    LEVEL_CLAN_TER_ON_WAR       = -441,         // 帮派领地争夺战进行中，不能进入领地
    CLAN_TER_WAR_FIN            = -442,         // 本轮帮派领地争夺战已结束
    CLAN_TER_NOT_OWN_AWD        = -443,         // 你没有帮派领地战奖励
    CLAN_TER_AWD_EXPIRE         = -444,         // 帮派领地战奖励已过期
    LEVEL_NOT_ENTER             = -445,         // 尚未进入过该副本
    LEVEL_NO_CLANCHL_REC        = -446,         // 目标帮派无宣战信息
    CANT_ENTER_OTHER_CLANCONQ   = -447,         // 不能进入其他帮派或防守方非下属帮派的奴役战争
    CLAN_TER_NOT_OWN_DALYAWD    = -448,         // 该帮派领地不能领取每日资源
    CLAN_TER_DALYAWD_FETCHED    = -449,         // 今天已经领取过该帮派领地每日资源
    
    ARENA_ALREADY_CHECKED_IN    = -450,         // 已经在竞技场排队了，不能再签入
    ARENA_ALREADY_IN            = -451,         // 已经加入竞技场了，不能再签入
    ARENA_JOIN_CHLVL_NOT_QUALIFY= -452,         // 未达到参加竞技场决赛资格
    ARENA_CHLVL_PLY_FULL        = -453,         // 竞技场决赛副本参加角色已达上限
    ARENA_CHLVL_FINISH          = -454,         // 本轮竞技场决赛已结束
    ARENA_AWD_EXPIRE            = -455,         // 竞技场决赛奖励已超时
    BTL_AWD_FETCHED             = -456,         // 已经领取过本次竞技场奖励了
    BTL_NOT_ON_BOARD            = -457,         // 本次竞技场排行未上板
    BLT_AWD_CONF_NOT_EXIST      = -458,         // 竞技场排行奖励配置不存在
    LEVEL_CANT_WIPE             = -459,         // 该副本不能扫荡
    LEVEL_WIPE_MAX_REACH        = -460,         // 副本扫荡队列已满
    LEVEL_WIPE_TIME_NOT_FIN     = -461,         // 副本扫荡完成时间未到
    MAX_LEVEL_WIPE_CNT_REACH    = -462,         // 已达到开启扫荡队列数上限
    WAIT_LVLWIPE_CANT_YBFIN     = -463,         // 等待队列中的扫荡副本不能立即完成扫荡

    MAX_OWN_PET_REACHED         = -501,         // 已达到最大拥有宠物上限，不能再拥有了
    PET_NOT_FOUND               = -502,         // 未找到指定宠物
    MAX_PET_GRID_REACHED        = -503,         // 已达到最大拥有宠物格子上限了
    NO_CUR_PET                  = -504,         // 没有出战宠物
    MAX_SKSLOT_REACHED          = -505,         // 当前宠物已达到最大拥有技能槽
    MAX_PET_SKILL_REACHED       = -506,         // 当前宠物已达到最大能学技能数
    NO_SKIL_TO_LEARN            = -507,         // 当前宠物在该宠物技能书中没有可学的技能了
    NO_SKIL_TO_LEARN_NOT_QUALIFY= -508,         // 该宠物技能书中尚有技能可学，但是当前宠物不满足要求
    PET_SKIL_NOT_FOUND          = -509,         // 宠物技能未找到
    PET_MAX_ACTP_REACHED        = -510,         // 宠物已达到最大疲劳值，无需再增加了
    PET_MAX_QUAL_REACHED        = -511,         // 宠物已达到最大品阶，不能再提升了
    PET_NEXT_QUAL_NOT_IN_ITEM   = -512,         // 该道具无法提升该宠物的品阶
    PET_ZERO_ACTP               = -513,         // 宠物行动力不足
    NOT_OWN_ANY_PET             = -514,         // 尚未拥有任何宠物
    NOT_OWN_SUCH_PET            = -515,         // 尚未拥有该宠物
    CANT_TRANS_CUR_PET_EXP      = -516,         // 当前出战宠物不能参与宠物转生
    NO_PET_EXP_TO_TRANS         = -517,         // 转生材料宠物没有经验值
    PET_MOD_EXP_ERROR           = -518,         // 修改宠物经验值出错
    PET_NO_GLD_CALL_CNT         = -519,         // 游戏币刷新小窝次数已用尽，无法再用游戏币刷新小窝了
    PET_CANT_MOVE_COMB_PET      = -520,         // 不能放逐合体宠物
    PET_NO_COMB_PET             = -521,         // 需要先进行宠物合体
    PET_NOT_IN_FIGHT_LADDER     = -522,         // 宠物不在宠物天梯
    PET_LADDER_BUSY             = -523,         // 宠物天梯消息过于频繁
    PET_CANT_PK_SELF            = -524,         // 宠物不能PK自己
    PET_PK_LEVEL_LIMIT          = -525,         // 宠物PK等级差限制
    PET_INVALID_PK_REC          = -526,         // 宠物PK记录不存在
    PET_PETPK_ZERO_CNT          = -527,         // 宠物PK挑战次数已用完
    PET_CANT_TRANS_COMB_PET     = -528,         // 不能转生合体宠物
    PET_NO_REACH_SKILL_LVL      = -529,         // 宠物的技能等级不足
    PET_ATTPER_REACH_REQ        = -530,         // 宠物资质不足
    PET_LVL_TOO_LOW             = -531,         // 宠物等级不够
    PET_SKIL_CNT_NOT_ENOUGH     = -532,         // 宠物技能数不足
    PET_QUAL_NOT_ENOUGH         = -533,         // 宠物品阶不足
    PET_RARITY_NOT_ENOUGH       = -534,         // 宠物稀有度不足
    PET_COLAWD_NOT_FIN          = -535,         // 宠物图鉴尚未收集完整
    PET_COLAWD_ALREADY_FETCH    = -536,         // 已获取过该宠物图鉴奖励
    PET_CANT_EVOLUTION          = -537,         // 该宠物不能进化了
    PET_EVOLUTION_TO_ERR        = -538,         // 不能进化成该目标宠物

    ACHIEVE_NO_ACHIEVE          = -560,          // 你没有获得该成就
    ACHIEVE_NO_AWD              = -561,          // 此成就没有奖励
    ACHIEVE_ALREAY_GOT_AWD      = -562,          // 你已领取过该成就的奖励

    MIS_COLM_NOT_REACHED        = -600,         // 探索未完成
    MIS_NOT_EXIST               = -601,         // 不存在该任务
    MIS_ALREADY_ACCEPT          = -602,         // 任务已接，不能重复接
    MIS_ALREADY_DONE            = -603,         // 任务已接完成了，不能再接了
    MIS_PREMIS_REQUIRE          = -604,         // 前置任务未完成
    MIS_ITEM_REQUIRE            = -605,         // 没有足够的所需道具
    MIS_NOT_ACCEPT              = -606,         // 任务还没接
    MIS_KM_NOT_REACHED          = -607,         // 次数没有达到
    MIS_TM_NOT_REACHED          = -608,         // 任务开启时间还未到
    MIS_TM_FINISHED             = -609,         // 任务时间已过
    MIS_CANT_ABORD              = -610,         // 任务不能放弃
    MIS_CANT_AUTOCOMIT          = -611,         // 任务不能委托
    MIS_KP_NOT_REACHED          = -612,         // 任务杀人数没达到
    MIS_PZKP_NOT_REACHED        = -613,         // 任务擂台杀人数没达到
    MIS_PZCKP_NOT_REACHED       = -614,         // 任务擂台连续杀人数没达到
    MIS_TM_OVER                 = -615,         // 任务已超时
    MIS_CANT_TRANS_WHEN_FLLOW   = -616,         // 有护送任务时不能传送
    MIS_CANT_BUY_INSURE         = -617,         // 任务不能买保险
    MIS_ALREDY_HAVE_INSURE      = -618,         // 任务已经有保险
    MIS_SKILL_INVALID           = -619,         // 任务技能不存在
    MIS_SKILL_IN_CD             = -620,         // 任务技能冷却中
    RMIS_MAX_QUAL               = -621,         // 任务酒馆已达最大品质
    RMIS_ACCEPT_TIMES_LIMIT     = -622,         // 酒馆任务接受次数限制
    RMIS_REFRESH_IN_CD          = -623,         // 任务酒馆刷新冷却中
    MIS_LEVEL_NOT_ENTER         = -624,         // 未进入过该副本
    MIS_NOT_FINED               = -625,         // 尚未完成过需要完成的任务
    RMIS_CLAN_ACEPT_ALREADY     = -626,         // 所在帮派已经接受过今天的酒馆任务了
    MIS_NEED_JOIN_CAMP          = -627,         // 尚未加入阵营
    MIS_CANT_TRANS_REDNM        = -628,         // 红名时不能传送
    MIS_CANT_BUY_DOUBLE         = -629,         // 此任务不能购买双倍奖励
    MIS_TIMES_NOT_REACHED       = -630,         // 任务次数未达到

    LVLMIS_NO_PRIZE             = -650,         // 侠客行副本任务没有奖励或已领取
    LVLMIS_PREMIS_REQUIRE       = -651,         // 前置侠客行副本任务未完成
    LVLMIS_NOT_FIN              = -652,         // 侠客行任务未完成

    MERI_NOT_EXIST              = -701,         // 经脉不存在
    MERI_ALREADY_ACTIVATE       = -702,         // 经脉已经开通
    MERI_ACUP_NOT_EXIST         = -703,         // 穴位不存在
    MERI_ACUP_ALREADY_ACTIVATE  = -704,         // 穴位已经开通
    MERI_NOT_ACTIVATE           = -705,         // 经脉尚未开启
    MERI_ACUP_OVER_QUALIFY      = -706,         // 道具中可升级的穴位等级大于等于道具指定最大等级，没有可升级的了
    MERI_ACUP_NOT_QUALIFY       = -707,         // 道具中可升级的穴位等级尚未满足道具指定的最低等级要求
    MERI_ACUP_ALL_ACTIVATE      = -708,         // 道具中的穴位全部已经开通了，没有可开通的穴位了
    MERI_ACUP_MAX_LVL_REACHED   = -709,         // 穴位达到最大等级了，不能再升级了
    MERI_ACUP_ALREADY_UPING     = -710,         // 穴位已经在升级中了
    MERI_ACUP_WRONG_ITEM        = -711,         // 不是穴位升级道具
    MERI_ACUP_NO_ACUP_TO_UP     = -712,         // 道具中没有可升级的穴位
    MERI_ACUP_NOT_ACTIVATE      = -713,         // 穴位尚未开启
    MERI_ACUP_LVL_NOT_ENOUGH    = -714,         // 穴位等级不足
    MERI_SEALED                 = -715,         // 经脉被封
    MERI_ACUP_SEALED            = -716,         // 穴位被封
    MERI_ACC_NO_ACUPUP          = -717,         // 没有在修炼中的经脉，无需加速
    MERI_NOT_ALL_ACUP_ACTIVE    = -718,         // 经脉尚有穴位没开通
    MERI_NO_MERI_ACTIVATE       = -719,         // 尚未开通任何经脉
    MERI_NO_ACUP_ACTIVATE       = -720,         // 尚未开通任何穴位
    MERI_CDCNT_REACHED          = -721,         // 无可用的修炼队列了，请等待修炼队列冷却
    MERI_NO_QUICK_FIN_CD        = -722,         // 没有需要快速完成的冷却队列
    MERI_MAX_CDCNT_REACHED      = -723,         // 已达到最大经脉修炼队列数量
    MERI_ADD_CDCNT_LEVEL_REQUIRE= -724,         // 角色等级不足，不能增加新的经脉修炼队列
    MERI_ACT_NEED_ITM           = -725,         // 本经脉需要开启道具才能开启
    MERI_ACUP_ACT_NEED_ITM      = -726,         // 本穴位需要开启道具才能开启
    MERI_POINT_NOT_ENOUGH       = -727,         // 经脉值不足

    BSTATE_SAME_TP_BSTATE_EXIST = -740,         // 已存在同类型的祝福状态了，不能再开启
    MAX_BSTATE_PAR_REACHED      = -741,         // 超出允许最大叠加祝福状态参数上限
    STATE_CONT_ADD_MORE         = -742,         // 该状态已达到最大叠加数
    STATE_HAS_BETTER_STATE      = -743,         // 你身上已有更强大的此类状态

    SKIL_NOT_EXIST              = -751,         // 技能不存在
    SKIL_NOT_LEARN              = -752,         // 尚未学会此技能
    SKIL_SKILL_UPPING           = -753,         // 技能已经在升级中了
    SKIL_SKILL_UP_WRONG_ITEM    = -754,         // 不是技能升级道具
    SKIL_NO_SKILL_TO_UP         = -755,         // 道具中没有可升级的技能
    SKIL_SKILLUP_OVER_QUALIFY   = -756,         // 道具中可升级的技能等级大于等于道具指定最大等级，没有可升级的了
    SKIL_SKILLUP_NOT_QUALIFY    = -757,         // 道具中可升级的技能等级尚未满足道具指定的最低等级要求
    SKIL_SKILL_CANT_EXP_UP      = -758,         // 技能无法再加点升级了
    SKIL_SKILL_EXP_NOT_ENOUGH   = -759,         // 技能点不足
    SKIL_SKILL_MAX_LVL_REACHED  = -760,         // 技能已经达到最大等级了
    SKIL_NO_SK_TO_LEARN         = -761,         // 该道具已经没有什么技能可学的了
    SKIL_LEARN_NOT_QUALIFY      = -762,         // 该道具还有可学技能，但是尚不符合学习要求
    SKIL_CANT_CAST              = -763,         // 当前角色还不能释放技能
    SKIL_CAST_TARGET_TYPE_ERR   = -764,         // 释放目标类型与配置不符
    SKIL_LVL_ERR                = -765,         // 技能等级数据错误
    SKIL_CD_NOT_REACH           = -766,         // 技能CD中
    SKIL_CAST_ITEM_REQUIRE      = -767,         // 没有足够的技能释放所需道具
    SKIL_TARGET_NOT_AVALIBLE    = -768,         // 目标不存在
    SKIL_TARGET_AVOID           = -769,         // 目标技能免疫
    SKIL_ALREADY_CASTING_SKILL  = -770,         // 吟唱中，不能再释放
    SKIL_CAST_EQUIP_REQUIRE     = -771,         // 没有装备释放技能所需装备
    SKIL_CAST_RANG_ERR          = -772,         // 不在施法范围内
    SKIL_CANT_CAST_WHEN_JUMP    = -773,         // 跳跃过程中不能施法
    SKIL_INVALIDE_TAREGET       = -774,         // 错误的技能释放目标
    SKIL_UP_YOU_LEVEL_REQUIRE   = -775,         // 角色等级不足，不能升级技能
    SKIL_SPT_UP_MAX_REACHED     = -776,         // 已达最大技能强化等级
    SKIL_ACC_NO_SKILUP          = -777,         // 没有在参悟中的技能，无需加速
    SKIL_CANT_APPLY_TO_DEADMEN  = -778,         // 技能不能对尸体释放
    SKIL_NOT_ACTIVED            = -779,         // 需抄录技能未抄录，不能释放
    SKIL_CANT_ACTIVE            = -780,         // 技能不能抄录
    MAX_ACTIVE_SKIL_REACHED     = -781,         // 已达到最大抄录技能数
    SKIL_ALREADY_ACTIVE         = -782,         // 技能已抄录
    SKIL_ALREADY_HOLDING_SKILL = -783,         // 聚气中，不能释放其它技术

    SKIL_NOT_LEARN_ANY_SECSKIL  = -790,         // 尚未学会任何秘技
    SKIL_NOT_LEARN_ANY_CARRSKIL = -791,         // 尚未学会任何门派技能
    SKIL_NOT_LEARN_SUCH_SKIL    = -792,         // 尚未学会该技能
    SKIL_SECSKIL_NOT_ENOUGH     = -793,         // 学会的秘籍数量不足
    SKIL_CARRSKIL_NOT_ENOUGH    = -794,         // 学会的门派技能数量不足
    SKIL_SPT_NOT_ENOUGH         = -795,         // 技能的强化值不足
    SKIL_SKLVL_NOT_ENOUGH       = -796,         // 技能的等级不足

    MAP_LINK_NOT_EXIST      = -801,             // 地图切换点不存在
    MAP_LINK_NOT_NEAR_BY    = -802,             // 地图切换点不在附近
    TARGET_MAP_NOT_EXIST    = -803,             // 目标地图不存在
    MAP_NOT_IN_COLAREA      = -804,             // 不在采集区域中
    MAP_COLAREA_CD          = -805,             // 区域采集过于频繁
    MAP_LINK_LEVEL_REQUIRE  = -806,             // 地图切换点等级需求不符

    DPITEM_NOT_EXIST        = -821,             // 掉落物品组不存在
    DPITEM_DISSAPPEARED     = -822,             // 掉落物品已经消失了
    DPITEM_NOT_NEAR_BY = -823,             // 掉落物品不在附近
    DPITEM_NOT_YOURS = -824,             // 掉落物品不属于你
    
    MKT_ITEM_SOLD_OUT       = -850,             // 商城中道具卖完了
    MKT_ITEM_NOT_ON_SAIL    = -851,             // 商城中道具没有上架
    MKT_ITEM_NOT_BEGIN_SELL = -852,             // 商城中道具还没开卖
    MKT_ITEM_MAX_BUY_REACHED= -853,             // 已达到每角色允许购买上限
    MKT_ITEM_SELL_TIME_OUT  = -854,             // 出售道具时间已到头

    ITEM_TP_NOT_EXIST       = -901,             // 该类型道具不存在
    ITEM_CANT_SELL          = -902,             // 道具不能出售
    ITEM_CD_NOT_REACH       = -903,             // 道具cd没有冷却
    ITEM_NO_FORGE_ATT       = -904,             // 装备没有锻造属性
    ITEM_FORGE_LIMIT_REACH  = -905,             // 达到最大锻造等级，不能再锻造了
    ITEM_CANT_EMBED         = -906,             // 装备没有孔，不能镶嵌
    ITEM_MAX_EMBED_REACH    = -907,             // 镶嵌满了，不能再镶嵌了
    ITEM_CANT_ADD_STATE     = -908,             // 目标不能再添加该状态了
    
    WPN_NOT_BREAK           = -910,             // 武器未被击碎
    EQP_DONT_NEED_REPAIR    = -911,             // 装备无需修复耐久
    COST_ITEM_CONFIG_MISSED = -912,             // 消耗道具配置出错
    EMBED_SAME_STONE        = -913,             // 不能再同一装备上镶嵌相同类型的宝石
    COST_ITEM_ERROR         = -914,             // 消耗道具出错
    FORGE_TRANS_TO_HIGH_FLVL= -915,             // 萃取目标装备锻造等级比源装备高
    FORGE_TRANS_NO_FLVL     = -916,             // 萃取源装备无锻造等级
    FORGE_TRANS_WITH_STONE  = -917,             // 萃取源装备镶嵌了宝石
    CANT_MERGE_DIFF_STONE   = -918,             // 不能合成不同类型的宝石
    CANT_MERGE_DIFF_LVL_STN = -919,             // 不能合成不同等级的宝石
    NOT_ENGOUH_MERGE_STN    = -920,             // 缺少合成所需最少宝石数
    MAX_STN_LVL_REACHED     = -921,             // 已达到最大宝石等级，不能再合成了
    CANT_MERGE_DIFF_QUAL_EQP= -922,             // 不能合成或打造不同品质的装备
    CANT_MERGE_NO_SUIT      = -923,             // 不能合成或打造非套装装备
    CANT_MERGE_DIFF_SUIT    = -924,             // 不能合成或打造不同套装装备
    TARGET_ITM_QUAL_ERR     = -925,             // 目标模具品质不对
    NO_TARGET_QUAL_SUIT     = -926,             // 没有对应品质的目标套装
    NO_TARGET_POS_EQP       = -927,             // 没有对应部位的装备
    MERGE_EQP_STN_LVL_ERR   = -928,             // 材料宝石等级不符
    MERGE_EQP_WITH_STN      = -929,             // 材料装备镶嵌有宝石，不能合成或打造
    EQP_UP_WITHOUT_TAR_ITM  = -930,             // 提升装备品质必须要有模具
    ITEM_NOT_DROPABLE       = -931,             // 道具不可丢弃
    CANT_SEND_SELF_GIFT     = -932,             // 不能购买赠送道具给自己
    ITEM_CUR_FORGE_LIMIT_REACH = -933,          // 达到当前能锻造的最大等级，不能再锻造了
    CUR_MAX_STN_LVL_REACHED = -934,             // 达到当前宝石合成的最大等级，不能再合成了
    FESHION_CANT_DIR_REPAIRE= -935,             // 时装不能直接修复
    ALREADY_FREE_LOTED      = -936,             // 已经进行过免费修行了
    EQP_CANT_DECOMPOSE      = -937,             // 装备不能分解
    ITEM_EXPIRE             = -938,             // 道具已过期
    EQP_EXPIRE              = -939,             // 装备已过期
    COSE_EQP_WITH_STN       = -940,             // 待消耗装备镶嵌有宝石，不能消耗
    UITEM_CORD_WRONG        = -941,             // 使用道具所需地图、坐标不对
    UITM_VIP_LVL_TOO_LOW    = -942,             // 已有vip等级大于道具vip等级，不能使用
    EQP_CANT_FORGE          = -943,             // 该装备不能锻造、镶嵌、分解
    LOTPT_NOT_ENOUGH        = -944,             // 修行祝福点数不足
    MAP_CANT_USEITEM        = -945,             // 当前场景不能使用道具
    EQP_CANT_ADD_ATT        = -946,             // 该装备不能追加属性
    EQP_ADD_ATT_LIMIT_REACH = -947,             // 已达到追加属性上限
    EQP_CANT_SUP_FORGE      = -948,             // 该装备不能高级强化
    EQP_SUP_FORGE_LIMIT_REACH = -949,           // 已达到高级强化上限
    EQP_WITHOUT_SUP_FRG_ATT = -950,             // 该装备没有指定的高级强化属性
    EQP_HAS_THE_ATT         = -951,             // 该装备已经拥有了此属性
    EQP_CANT_ACT_ATT380     = -952,             // 该装备不能激活380属性
    EQP_CANT_REPAIR         = -953,             // 该装备不能修复
    EQP_CANT_VERI           = -954,             // 该装备不需要鉴定
    EQP_SUP_FRG_ATT_FLVL_ERR = -955,            // 该装备没有达到激活此属性需要的条件
    EQP_CANT_EXCHANGE       = -956,             // 该装备不能洗练
    EQP_NOT_THIS_ATT        = -957,             // 该装备没有该属性
    EQP_CANT_CHARGE_POWER   = -958,             // 该装备不能充能
    EQP_REACH_MAX_POWERPT   = -959,             // 该装备已达到充能上限
    EQP_LIMIT_TM_CANT_BLEND = -960,             // 时效装备不可融合
    EQP_BLEND_SAME_ITEM     = -961,             // 已融合相同类型物品
    EQP_CANT_BLEND          = -962,             // 该装备不可融合
    EQP_CANT_CHANGE_APPEARANCE = -963,          // 该装备不可幻化
    EQP_NOT_BLEND_THIS      = -964,             // 未融合该类型装备，不可幻化
    EQP_HAD_ADD_EXATT       = -965,             // 该装备已增加过卓越属性
    EQP_CANT_ADD_EXATT      = -966,             // 该装备不能增加卓越属性
    EQP_REACH_MAX_EXATT     = -967,             // 该装备已到达卓越属性条数限制
    ITM_CANT_ADD_EXATT      = -968,             // 该道具不能用于增加卓越属性
    UITEM_CNT_NOT_ENOUGH    = -969,             // 道具使用次数不足
    ENERGY_TOPLIMIT         = -970,             // 体力上限    
 
    ITEM_NOT_IN_SHOP = -997,                    // 商城没有此类道具
    NOT_ENOUGH_GIFT = -998,                     // 没有足够的礼金
    NOT_ENOUGH_NOBPT = -999,                    // 没有足够的声望
    NOT_ENOUGH_BATPT = -1000,                   // 没有足够的古战场积分
    NOT_ENOUGH_YB           = -1001,            // 没有足够的元宝
    NOT_ENOUGH_GOLD         = -1002,            // 没有足够的金币
    ITEM_REQUIRE            = -1003,            // 没有足够的所需道具
    TARGET_USER_NOT_EXIST   = -1004,            // 目标用户不在线
    YOUR_IN_TARGET_BLACKLIST= -1005,            // 你被目标用户拉入黑名单了
    NOT_ENOUGH_BNDYB        = -1006,            // 没有足够的礼券
    PACKAGE_ITEM_REQUIRE    = -1007,            // 背包中没有足够的所需道具
    NOT_ENOUGH_HONER        = -1008,            // 荣誉值不足
    NOT_ENOUGH_CLANG        = -1009,            // 帮派货币不足
    NOT_ENOUGH_ACT_V        = -1010,            // 角色行动力不足
    NOT_ENOUGH_YBPT         = -1011,            // 商城积分不足
    NOT_ENOUGH_PETPT        = -1012,            // 宠物天梯积分不足
    GOLD_UPPER_LIMIT        = -1013,            //你的金币已达上限，不能再获得更多了
    INT_UPPER_LIMIT         = -1014,            //已达数值上限，不能再增加更多了
    NOT_ENOUGH_LOTPT        = -1015,            // 寻宝积分不足
    NOT_ENOUGH_ARENA_PT     = -1016,            // 竞技场积分不满足

    NPC_YOU_ARE_REDNM           = -1050,        // 红名不能购买NPC道具
    NPC_NOT_IN_MAP              = -1051,        // 该NPC不在当前地图中
    NPC_TOO_FAR_AWAY            = -1052,        // NPC距离太远了
    NO_SUCH_NPC                 = -1053,        // 没有这个NPC
    NPC_NO_ITEM_SELL            = -1054,        // 该NPC没有道具交易
    NPC_NO_SUCH_ITEM            = -1056,        // 该NPC没有该道具出售
    NPC_NOT_NEAR_BY             = -1057,        // NPC不在附近
    NPC_DONT_FORGE              = -1058,        // NPC不锻造
    NPC_DONT_EMBED              = -1059,        // NPC不镶嵌
    NPC_DONT_REPAIR_WPN         = -1060,        // NPC不修复击碎武器
    NPC_DONT_REPAIR_EQP         = -1061,        // NPC不修复装备耐久
    NPC_NO_LVL_ENTRY            = -1062,        // NPC没有副本入口
    NPC_NO_MAP_TRANS            = -1063,        // NPC没有地图传送配置
    NPC_NO_TAR_TRANS_PT         = -1064,        // NPC没有目标传送点配置
    NPC_NO_REPO                 = -1065,        // 该NPC没有仓库入口
    NPC_NO_STATE                = -1066,        // 该NPC处没有你想获取的状态
    NPC_ADD_STATE_ERR           = -1067,        // 增加状态出错，可能你已有该状态
    NPC_BUY_NOT_IN_CLANTER      = -1068,        // 进入攻城战后，才能购买
    NPC_CANT_TRANSTO            = -1069,        // 不能传送到该地图

    NO_MARK_CONF                = -1100,        // 没有对应配置
    PACKAGE_SPACE_NOT_ENOUGH    = -1101,        // 没有足够的背包空间了
    NOT_OWN_ITEM                = -1102,        // 你没有这个道具
    ITEM_NOT_IN_SOLD_LIST       = -1103,        // 道具不在已出售道具列表中
    ITEM_COUNT_NOT_ENOUGH       = -1104,        // 道具数量不足
    CANT_COMBINE_DIFFERENT_ITEM = -1105,        // 不能叠加不同类型的道具
    MAX_OWN_ITEM_REACHED        = -1106,        // 已达到该道具可拥有最大上限
    ITEM_COMBIN_MAX_REACHED     = -1107,        // 已达到最大可叠加上限
    MAX_PACKAGE_SPACE_REACHED   = -1108,        // 已经达到最大背包空间了
    CANT_COMBINE_DIFF_BIND_ITEM = -1109,        // 绑定与非绑定道具不能叠加
    MAX_REPO_SPACE_REACHED      = -1110,        // 已经达到最大仓库空间了
    NO_PREPO                    = -1111,        // 没有随身背包,不能存取道具
    REPO_SAPCE_NOT_ENOUGH       = -1112,        // 仓库空间不足
    PREPO_ALREADY_ENBALED       = -1113,        // 随身仓库已经开启，无需再开启
    NO_SUCH_PACKAGE_ITEM        = -1114,        // 背包中没有这个道具
    NO_SUCH_AUCTION_ITEM        = -1115,        // 商铺中没有这个道具
    AUCTION_ITEM_EXPIRE         = -1116,        // 商铺道具已过期
    CANT_SELL_BIND_ITEM         = -1117,        // 不能出售绑定道具
    AUCTION_NO_MONEY_TO_FETCH   = -1118,        // 商铺中没有资金可以获取
    AUCTION_CANT_ADD_ITEM       = -1119,        // 不能再上架道具了
    MAX_AUCTION_SPACE_REACHED   = -1120,        // 已达到最大商铺上限了
    NOT_HONER_ITEM              = -1121,        // 不是荣誉商城的道具
    TEMPREPO_SPACE_NOT_ENOUGH   = -1122,        // 临时仓库空间不足
    NOT_YBPT_ITEM               = -1123,        // 不是积分商城的道具
    CANT_COMBINE_EXPIRE_ITEM    = -1124,        // 不能合并时效道具
    AUCTION_QUERY_BUSY          = -1125,        // 商铺道具查询过于频繁
    NOT_EXPIRE_ITEM             = -1126,        // 不是时效道具
    NEED_DELAY_EXPIRE_ITEM      = -1127,        // 需要延时道具
    MAX_DALY_HEXP_REACHED       = -1128,        // 已达到每日可获取的最大荣誉值，不能再增加荣誉值了
    MAX_ACTV_REACHED            = -1129,        // 已达到最大体力值，不能再增加体力值了
    MAX_SKEXP_REACHED           = -1130,        // 已达到最大气海值，不能再增加了
    NOT_ENCHANT_EQP             = -1131,        // 不是镀金装备
    ENCHANT_EXISIT              = -1132,        // 已镀金
    EQP_FOLLW_NOT_FIND          = -1133,        // 跟随装备未穿上或没有该装备
    LOTTERY_TM_NOT_ACT          = -1134,        // 不在抽奖有效时间段
    NOT_LOTTERY_ITEM            = -1135,        // 不是寻宝积分商城的道具
    MAX_WHLVL_REACHED           = -1136,        // 增加武魂失败，已达到当前最大可升等级
    MAX_DITM_ADDCNT             = -1137,        // 挂售失败，已达到每日挂售上限
    MAX_DITM_BUYCNT             = -1138,        // 购买失败，已达到每日购买上限
    NO_LOTTERY_CNT              = -1139,        //  抽奖次数不足

    QUALIFY_CARR_ERR            = -1201,        // 职业要求不符
    QUALIFY_SEX_ERR             = -1202,        // 性别要求不符
    QUALIFY_SOME_ATT_ERR        = -1203,        // 某些属性不符 // TO DO : 细化不符合属性错误信息
    QUALIFY_LEVEL_ERR           = -1204,        // 等级要求不符
    QUALIFY_STR_ERR             = -1205,        // 力量要求不符
    QUALIFY_CON_ERR             = -1206,        // 体力要求不符
    QUALIFY_INTE_ERR            = -1207,        // 智力要求不符
    QUALIFY_AGI_ERR             = -1208,        // 敏捷要求不符
    QUALIFY_WIS_ERR             = -1209,        // 统率要求不符
    QUALIFY_ACHIVE_ERR          = -1210,        // 成就要求不符
    QUALIFY_LOTCNT_ERR          = -1211,        // 修行次数不符合要求
    QUALIFY_MERGE_ERR           = -1212,        // 没有成功过符合要求的合成
    QUALIFY_GMIS_FIN_ERR        = -1213,        // 尚有需要完成的苍穹目标未完成
    QUALIFY_MLMIS_ERR           = -1214,        // 侠客行称号要求不符
    QUALIFY_CARRLVL_ERR         = -1215,        //职业等级不符合要求
    QUALIFY_RESETLVL_ERR        = -1216,        // 转生次数不符合要求
    QUALIFY_FINMIS_ERR          = -1217,        // 没有完成指定任务

    EQP_FLVL_NOT_ENOUGH         = -1240,        // 装备锻造等级要求不符
    EQP_STNCNT_NOT_ENOUGH       = -1241,        // 装备宝石镶嵌数要求不符
    WPN_BCNT_NOT_ENOUGH         = -1242,        // 武器击碎其他武器数要求不符
    WPN_KCNT_NOT_ENOUGH         = -1243,        // 武器击杀数要求不符
    EQP_POS_QUAL_NOT_ENOUGH     = -1244,        // 未拥有该类装备或品质不足
    NOT_WARE_QUAL_EQP           = -1245,        // 尚未装备指定品质装备
    NOT_WARE_FLVL_CNT_ENOUGH    = -1246,        // 未穿戴指定装备,或该装备强化等级不足
    NOT_WARE_EXATT_CNT_ENOUGH   = -1247,        // 未穿戴指定装备, 装备追加属性条数不足
    NOT_WARE_TARGET_EQP         = -1248,        // 未穿戴指定装备


    ALREADY_YOUR_BUDDY      = -1251,    // 已经是你好友了
    ALREADY_YOUR_FOE        = -1252,    // 已经是你仇人了
    ALREADY_YOUR_BLACKLIST  = -1253,    // 已经在黑名单中了
    CANT_ADD_SELF_CHARACTER = -1254,    // 不能添加自己的角色
    MAX_FRIEND_REACHED      = -1255,    // 已达到最大好友数
    MAX_BLACK_LIST_REACHED  = -1256,    // 已达到最大黑名单数
    MAX_CONGCNT_REACHED     = -1257,    // 已达到最大祝贺好友数
    MAX_CONGCNT_ACCEPTED    = -1258,    // 对方接受祝贺数已达上限
    NOT_CONG_DATA           = -1259,    // 没有对应的升级祝贺记录
    NOT_LVL_UPCONG          = -1260,    // 没有可以获取经验的祝贺了
    NOT_ENOUGH_FRIENDS      = -1261,    // 没有足够的好友
    NO_CONG_BEXP            = -1262,    // 祝福瓶中无经验了
    CONG_BEXP_GET           = -1263,    // 已经获取过祝福瓶经验了
    MAX_FRIEND_APPLY_REACHED= -1264,   // 已达到最大好友申请数
    O_MAX_FRIEND_REACHED    = -1265,   // 对方已达到最大好友数
    WRONG_CHARACTER_NAME    = -1266,   // 输入姓名错误
    ALREADY_APPLY_BUDDY     = -1267,   // 已经申请该好友
    CANT_CHAT_SELF          = -1268,   // 不能和直接聊天
    ALREAD_APPLY_YOUR_BUDDY = -1269,   // 对方已申请你为好友
    BUDDY_RECOMMENT_TOO_BUSY= -1270,   // 好友推荐太频繁

    TEAM_NO_MORE_TEAM       = -1301,    // 无法创建更多队伍了
    MAX_REQ_JOIN_REACH      = -1302,    // 达到加入最大申请数
    REQ_JOIN_NOT_FOUND      = -1303,    // 未找到加入申请
    REQ_JOIN_EXIST          = -1304,    // 已经申请过了
    NOT_YOUR_TEAM           = -1305,    // 不是队长
    MAX_REQ_IJOIN_REACH     = -1306,    // 达到加入最大邀请数
    REQ_IJOIN_NOT_FOUND     = -1307,    // 未找到加入邀请
    REQ_IJOIN_EXIST         = -1308,    // 已经邀请过了
    NOT_IN_TEAM             = -1309,    // 不在队伍中
    MEMBER_NOT_IN_TEAM      = -1310,    // 对方不在队伍中
    TEAM_NOT_EXIST          = -1311,    // 队伍不存在
    MAX_PUB_TEAM_REACHED    = -1312,    // 已达到最大发布数
    TEAM_ALRADY_PUBED       = -1313,    // 队伍已经发布过了
    TEAM_NOT_PUBED          = -1314,    // 队伍尚未发布
    TEAM_CHARACTER_NOT_EXIST= -1315,    // 角色不存在或已离线
    TEAM_MEMBER_FULL        = -1316,    // 队伍人满了
    TEAM_ALREADY_IN_TEAM    = -1317,    // 已经在队伍中了
    TAR_ALREADY_IN_TEAM     = -1318,    // 对方已经在队伍中了
    TEAM_CANT_KICK_SELF     = -1319,    // 不能踢自己
    TEAM_LEADER_SELF        = -1320,    // 自己是队长，不用替换
    TEAM_DROP_NOT_EXIST     = -1321,    // 该队伍掉落物品不存在
    TEAM_NOT_YOUR_DROP      = -1322,    // 不是你的队伍掉落物品，无权参与roll
    TEAM_DROP_ALREADY_ROLL  = -1323,    // 已经roll过了
    TEAM_CANT_JOIN          = -1324,    // 目标队伍已不能申请加入

    TRADE_SELF_INTRADE      = -1351,    // 自己已经在交易中了
    TRADE_TARGET_INTRADE    = -1352,    // 对方已经在交易中了
    TRADE_NO_TRADE_REQ      = -1353,    // 交易请求不存在
    TRADE_NOT_IN_TRADE      = -1354,    // 不在交易中
    TRADE_LOCKED_ADD_ITEM   = -1355,    // 交易已锁定，不能再添加物品
    TRADE_ITEM_ALREADY_IN_TRADE = -1356, // 物品已经在交易中了
    TRADE_CANT_DONE_WITHOUT_LOCK= -1357, // 不能在双方未锁定情况下完成交易
    TRADE_CANT_TRADE_SELF   = -1358,    // 不能与自己交易
    TRADE_BIND_ITEM         = -1359,    // 道具已绑定，不能交易
    TRADE_ITME_CNT_WRONG    = -1360,    // 交易道具数量不一致
    TRADE_GOLD_UPPER_LIMIT  = -1361,    // 交易后金币将超出上限
    TRADE_GOLD_TOO_MUCH     = -1362,    // 交易金币数量过大
    TRADE_YB_TOO_MUCH       = -1363,    // 交易元宝数量过大

    CLAN_CREATE_LVL_REQUIRE = -1400,    // 等级不足,不能创建帮派
    CLAN_ALREADY_IN_CLAN    = -1401,    // 已经在某个帮派中了
    NOT_CLAN_CREATE_ITEM    = -1402,    // 不是帮派创建道具
    CLAN_MEMBER_FULL        = -1403,    // 帮派成员已满
    CLAN_ALREADY_REQ_JOIN   = -1404,    // 已经申请过加入该帮派
    JOIN_CLAN_LVL_REQUIRE   = -1405,    // 等级不足,不能加入帮派
    NOT_IN_CLAN             = -1406,    // 你不是帮派成员
    CLAN_NO_AUTHORITY       = -1407,    // 你的帮派权限不够
    NO_SUCH_JOINCLAN_REQ    = -1408,    // 加入帮派申请不存在
    TARGET_ALREADY_IN_CLAN  = -1409,    // 对方已经在某个帮派中了
    CLAN_PRESIDENT_CANT_LEAVE=-1410,    // 帮主不能离开帮派
    MAX_CLAN_LVL_REACHED    = -1411,    // 帮派已达到最大等级
    CLAN_YB_NOT_ENOUGH      = -1412,    // 帮派元宝不足
    CLAN_GLD_NOT_ENGOUTH    = -1413,    // 帮派游戏币不足
    NOT_IN_YOUR_CLAN        = -1414,    // 目标不在你的帮派中
    CHANGE_SAME_CLANC       = -1415,    // 帮派职务一致，无需调整
    CLAN_VP_FULL            = -1416,    // 副帮主职位人数已满
    CLAN_PLY_NOT_ENOUGH     = -1417,    // 帮派人数不足
    CLAN_DISMIS_PLYCNT_ERR  = -1418,    // 帮派成员不满足解散最低成员数要求
    CLAN_NOT_EXIST          = -1419,    // 帮派不存在 
    SAME_NAME_CLAN_EXIST    = -1420,    // 已存在同名帮派
    CLAN_LVL_REQUIRE        = -1421,    // 帮派等级不够
    CLAN_MAX_YBAPERDAY_REACH= -1422,    // 每日捐献元宝数量达到上限
    CLAN_MAX_GLDAPERDAY_REACH=-1423,    // 每日捐献游戏币数量达到上限
    CLAN_CLANA_NOT_ENOUGH   = -1424,    // 帮派贡献不足 
    CLAN_JOIN_REQ_FULL      = -1425,    // 加入帮派申请已满
    CLAN_RNK_NOT_ENOUGH     = -1426,    // 帮派排名不足
    CLAN_TECH_MAXLVL_REACH  = -1427,    // 已达到最大帮派科技等级
    NOT_CLAN_TECH_PROC_ITM  = -1428,    // 不是帮派科技建设类道具
    TECHPROC_CNT_NOT_ENOUGH = -1429,    // 今天的帮派科技升级次数已用完
    TECHPROC_CD_NOT_REACH   = -1430,    // 帮派科技升级cd未到
    CLAN_TECH_NOT_ACTIVE    = -1431,    // 帮派尚未拥有该科技
    SUPLY_FETCH_TM_NOT_REACH= -1432,    // 尚未到获取粮草的时间
    CLAN_STAT_ALREADY_ACT   = -1433,    // 已激活该帮派科技状态
    CLAN_CLANPLLVL_REQUIRE  = -1434,    // 帮派官阶需求不符
    CLAN_MKT_LVL_REQUIRE    = -1435,    // 帮派商店等级不符合要求
    CLAN_TECH_CANT_USE      = -1436,    // 该帮派科技不能主动激活
    CLAN_AWD_ALREADY_FETCH  = -1437,    // 今天的俸禄已经领取
    CLAN_CALL_WRONG_LVL     = -1438,    // 当前副本不能进行帮派召集 
    CLAN_CHALENGE_NOT_OPEN  = -1439,    // 帮派宣战时间未到，不能宣战
    CLAN_CHALENGE_LVL_REQUIRE=-1440,    // 帮派宣战帮派等级不足
    CLAN_CHALENGE_TAR_LVL_REQUIRE=-1441,// 帮派宣战目标帮派等级不足
    CLAN_CANT_CHL_SELF      = -1442,    // 不能向自己帮派宣战
    CLAN_CANT_CHL_CHLED_CLAN= -1443,    // 已有约战的帮派不能宣战或被宣战
    CLAN_CHL_TECH_NEED      = -1444,    // 帮派宣战科技（设施）尚未开启
    CLAN_CONQED_FULL        = -1445,    // 下属帮派已满，不能再宣战
    CLAN_CANT_CHL_CONQED    = -1446,    // 不能向自己的下属帮派宣战
    CLAN_DISMIS_NOT_CONQED  = -1447,    // 不是下属帮派，无需解除
    CLAN_CHALENGE_LVL_DIST  = -1448,    // 帮派等级差过大，不能宣战
    CLAN_CANT_IMPEACH_YET   = -1449,    // 帮主3天内有上线，不能弹劾
    NOT_IMPEACH_ITEM        = -1450,    // 不是弹劾帮主道具
    CLAN_JOIN_CAMP_NOT_SAME = -1451,    // 非同一阵营帮派，不能加入
    ALREADY_JOIN_CAMP       = -1452,    // 已经在某个阵营中了
    CAMP_NOT_EXIST          = -1453,    // 不存在的阵营
    CAMP_AWD_ALREADY_FETCHED= -1454,    // 已领取过随机阵营奖励
    NOT_IN_CAMP             = -1455,    // 未加入阵营
    CLAN_RAID_NOT_CRT       = -1456,    // 帮派副本尚未创建，需帮主、长老创建后才能进入
    CLANTER_NO_COST_AWD     = -1457,    // 该攻城战没有消耗奖励
    CLANTER_COST_AWD_FETCHED = -1458,   // 已领取过该攻城战的消耗奖励
    CLANTER_COST_AWD_EXPIRE = -1459,    // 该攻城战的消耗奖励已过期
    CLANTER_NOT_REPAIR_MON  = -1460,    // 该攻城战没有需要修理的建筑
    CLANTER_NEED_NOT_REPAIR = -1461,    // 该建筑已修理好了
    CLANTER_NEED_NOT_REQUEST= -1462,    // 该攻城战不需要申请进入
    CLANTER_REQUEST_EXPIRE  = -1463,    // 申请攻城战时间已过
    CLANTER_CLAN_NEED_NOT_REQUEST=-1464,// 下次攻城战, 你所在的帮派不需要申请就可进入
    CLANTER_CLAN_ALREADY_REQUEST=-1465, // 你所在的帮派已申请过了
    CLANTER_CLAN_NOT_REQUEST= -1466,    // 你所在的帮派没有申请攻城战, 不能进入
    CLANTER_CLAN_NOT_WAR    = -1467,    // 没有帮派申请攻城，不需要守城
    CLAN_POINT_NOT_ENGOUTH  = -1468,    // 没有足够的消费点
    CLAN_ALREADY_START_DISMIS =-1469,   // 帮派已经开始解散
    SAME_LOGO                 =-1470,   //  标志未更改

    RACT_NOT_OPEN_OR_EXPIRE         = -1500,    // 排行活动未开启或已过期
    RACT_NOT_ON_BOARD               = -1501,    // 未上排行榜，不能领取奖励
    RACT_RANK_NO_FINAWARD           = -1502,    // 你的名次没有最终排名奖励
    RACT_ALREADY_GET_FINAWD         = -1503,    // 已经领取过最终排名奖励了
    RACT_ALREADY_GET_DALYAWD        = -1504,    // 已经领取过每日奖励了
    RACT_NO_DALYAWD                 = -1505,    // 该活动没有每日奖励
    RACT_GET_AWARD_NOT_FIN          = -1506,    // 活动进行中，不能获取最终奖励 
    RACT_NO_FINAWD                  = -1507,    // 该活动没有最终奖励
    RACT_GET_FINAWD_EXPIRE          = -1508,    // 最终奖励已超时，不能领取
    AACT_NOT_HAVE_AWD               = -1509,    //该活动奖励已被领取完了
    AACT_ALREADY_GET_AWD            = -1510,    //你已经领取过该奖励了
    AACT_ITEM_ALREADY_GET_AWD       = -1511,    //用于领奖装备的此奖励已被玩家领过了
    FACT_NOT_HAVE_AWD               = -1512,    //你已领取完该奖励
    FACT_RELYAWD_NOT_GOT            = -1513,    //你还不能领取该奖励，依赖目标未完成

    CACT_RANK_NO_FINAWARD           = -1520,    // 你所在帮派的名次没有最终排名奖励

    VIP_NOT_VIP                     = -1550,    // 你不是vip
    VIP_LVL_NOT_ENOUGH              = -1551,    // vip等级不足
    VIP_ALREADY_GET_RITM            = -1552,    // 今天已经领取过奖励了(随机奖励)
    VIP_ALREADY_GET_AITM            = -1553,    // 今天已经领取过奖励了(固定奖励)
    VIP_NO_RITM                     = -1554,    // 当前vip等级无每日随机奖励
    VIP_NO_AITM                     = -1555,    // 当前vip等级无每日固定奖励
    VIP_NO_PTRADE                   = -1556,    // 当前vip等级无法进行随身交易
    VIP_NO_PREP_DURA                = -1557,    // 当前vip等级无法进行随身修理
    VIP_NO_PREP_WPN                 = -1558,    // 当前vip等级无法进行随身武器修复
    VIP_NO_FREE_OFLAWD              = -1559,    // 当前vip等级无法免费领取离线经验奖励
    VIP_NO_LOT                      = -1560,    // 当前vip等级没有免费修行
    VIP_ALREADY_LOT                 = -1561,    // 今天已经进行过免费修行了
    VIP_ALREADY_GET_BNDYB           = -1562,    // 今天已经领取过绑定元宝了
    VIP_NO_DALY_BNDYB               = -1563,    // 当前vip等级无法领取每日绑定元宝奖励
    PVIP_ALREADY_GET_DAWD           = -1564,    // 今天的黄钻奖励已经领取过了
    VIP_NOT_PVIP                    = -1565,    // 你不是黄钻
    PVIP_ALREADY_GET_AWD            = -1566,    // 你已经领取过该黄钻礼包了
    PVIP_CANT_GET_LMAWD_YET         = -1567,    // 当前还不能领取该黄钻礼包
    VIP_NOT_YPVIP                   = -1568,    // 你不是年费黄钻

    LVLPRIZE_ALREADY_FETCHED        = -1600,    // 已经领取过该等级奖励了
    LVLPRIZE_NOT_EXIST              = -1601,    // 等级奖励不存在
    LVLPRIZE_LEVEL_REQUIRE          = -1602,    // 领取等级奖励角色等级不足

    ALL_DAY_SIGNIN                  = -1617,    // 没有补签次数
    TODAY_ALREADY_SIGNIN            = -1618,    // 今天已经签过到了
    SIGNIN_AWD_ALREADY_FETCHED      = -1619,    // 已经领取过该签到奖励了
    CLOGAWD_ALREADY_FETCHED         = -1620,    // 今天已经领取过登陆奖励了
    IVT_DAWD_ALREADY_FETCHED        = -1621,    // 今天已经领取过邀请奖励了
    IVT_AWD_ALREADY_FETCHED         = -1622,    // 该好友邀请奖励已获取过了
    IVT_LVL_CNT_REQUIRE             = -1623,    // 符合条件的已邀请好友数量不足      
    FEED_DMIS_ALREADY_GET           = -1624,    // 已领取今日必做分享奖励
    FEED_GMIS_ALREADY_GET           = -1625,    // 已领取该苍穹目标分享奖励
    FEED_GMIS_NOT_FIN               = -1626,    // 该苍穹目标尚未达成
    WHEXP_AWD_NOT_IN_BOARD          = -1627,    // 未上每周荣誉榜
    WHEXP_AWD_ALREADY_FETCH         = -1628,    // 已经领取每周荣誉榜奖励
    WHEXP_AWD_CONF_NOT_EXIST        = -1629,    // 每周荣誉奖励配置不存在
    ARENA_CWIN_AWD_FETCHED          = -1630,    // 已经领取过该连胜奖励了

    WH_NOT_ENOUGH_PKG_SPACE         = -1700,    // 武魂背包空间不足
    WH_NOT_ENOUGH_TMP_SPACE         = -1701,    // 武魂掉落空间不足
    WH_LVL_NOT_ACTIVE               = -1702,    // 武魂等级未激活
    WH_NOT_EXIST                    = -1703,    // 武魂不存在
    WH_NO_SPACE_TO_EXPANDE          = -1704,    // 武魂背包已没有扩充空间
    WH_NOT_ENOUGH_QUALITY           = -1705,    // 武魂品质不足
    WH_NOT_ENOUGH_LEVEL             = -1706,    // 武魂等级不足
    WH_NO_GOLD_HUNT_TIMES           = -1707,    // 武魂游戏币猎魂次数用尽
    WH_NOT_ENOUGH_WARE_SPACE        = -1708,    // 武魂装备空间不足位置受限
    WH_SAME_ID_EQUIPED              = -1709,    // 已装备同类武魂，不能再装备
    WH_NO_YB_ACTIVE_TIMES           = -1710,    // 武魂元宝激活次数用尽
    WH_ALREADY_ACTIVED              = -1711,    // 武魂等级已激活
    WH_REACH_MAX_LVL                = -1712,    // 武魂道具已达到最大等级

    QUERY_BUSY                      = -1719,    // 查询过于频繁
    MYSK_ALREADY_PUBLISHED          = -1720,    //你已经发布过结缘了
    MYSK_NO_PUBLISHED               = -1721,    //你没有发布过结缘
    MYSK_CANT_REQUEST_SELF          = -1722,    // 不能申请自己发布的结缘
    MYSK_PUBLISHED_NO_EXIT          = -1723,    //此结缘信息已过期
    MYSK_REQUEST_FULL               = -1724,    //此玩家接收的申请已满
    MYSK_REQUEST_ALREADY_REQ        = -1725,    //你已经向此玩家申请过了  
    MYSK_REQUEST_NO_EXIT            = -1726,    //没有此申请信息
    MYSK_ALREADY_MARRY              = -1727,    //你已经结婚了
    MYSK_PLY_ALREADY_MARRY          = -1728,    //此玩家已经结婚了

    MARRY_NOT_MARRY                 = -1730,    //你没有结缘
    MARRY_LVL_FULL                  = -1731,    //已达到结缘最大等级
    MARRY_DLG_CNT_EMPTY             = -1732,    // 你今天的结缘互动次数已用完

    SAFE_ACOUNT_NOT_ACTIVE          = -1800,    //你还没有开通帐号保护功能
    SAFE_ACOUNT_SCODE_ERR           = -1801,    //安全密码错误
    SAFE_ACOUNT_PHONE_ERR           = -1802,    //与获取验证码的手机号码不匹配
    SAFE_ACOUNT_TCODE_ERR           = -1803,    //验证码错误
    SAFE_ACOUNT_NO_TESTINFO         = -1804,    //没有产生验证信息
    SAFE_ACOUNT_SCODE_IS_EMPTY      = -1805,    //安全密码不能为空
    SAFE_ACOUNT_SCODE_TOO_LONG      = -1806,    //安全密码太长
    SAFE_ACOUNT_ALREADY_ACTIVE      = -1807,    //你已开通了帐号保护功能
    SAFE_ACOUNT_LOCKED              = -1808,    //你的账号处于安全锁定状态
    SAFE_ACOUNT_GOT_AWD             = -1809,    //你已领取了此奖励

    NOB_MAX_LVL_REACHED             = -1830,    //你已达到最大爵位等级

    WORSHIP_CNT_EMPTY               = -1840,    //你今天的膜拜次数已用完
    WORSHIP_NOT_OPEN                = -1841,    //膜拜时间未到
    WORSHIP_NOT_LVLCONF             = -1842,    //你所处的等级不能进行该膜拜

    ACHIVE_ALREADY_HAS              = -1850,    //你已拥有此称号
    ACHIVE_ALREADY_WITHOUT          = -1851,    //没有该称号

    RESETLVL_LVL_ERR                = -1860,    //转生等级不够
    RESETLVL_PT_USED                = -1861,    //洗练点数已使用了
    PVIP_POW_PT_NEED                = -1865,    //黄钻能量不足
    PVIP_POW_PT_TOTAL_NEED          = -1866,    //黄钻能量累计总点数不足
    PVIP_POW_CHG_CNT_NEED           = -1867,    //兑换次数不足
    PVIP_POW_NOT_ACT                = -1868,    //不在活动时间内   
    RSTORE_REQUEST_EXPIRE           = -1869,    //藏宝阁刷新时间未到

    
    BS_CONNECT_FAIL                 = -1900,    //联接跨服战失败
    BS_DIS_CONNECT                  = -1901,    //跨服战联接断开
    BS_IN_BATTLE_CNT_DO             = -1902,    //在跨服战中，不能进行此操作
    BS_IN_BATTLE_CNT_UITEM          = -1903,    //在跨服战中，不能使用此物品
    BS_IN_BATTLE_NT_ADULT           = -1904,    //你没有通过身份认证

    NOT_GM                          = -2001,              // 非GM
    GM_CMD_NOT_EXIST                = -2002,              // GM命令错误
    GM_AUTHORITY_NOT_ENOUGH         = -2003,              // GM权限不够
    GM_FOBT_LVL_TO_HIGH             = -2004,              // 新手指导员只能禁言30级以下用户
    GM_FOBT_NOT_CNT_LEFT            = -2005,              // 今天的禁言次数已经用完了

    FB_VIP_AWD_GOT                  = -2100,              // 已领过首次vip奖
    FB_VIP_AWD_NEED                 = -2101,              //  首次vip奖信息未记录

    ITM_USE_NOT_ROR_MOUNT           = -2111,              //  物品不能使用于坐骑升级
    NOT_FIT_MOUNT_QUAL              = -2112,              //  物品要求坐骑等阶不符
    MOUNT_NEED_ACT                  = -2113,              //  坐骑未激活
    MOUNT_LVL_MAX                   = -2114,              //  坐骑最顶级了
    LVLMIS_ONCE                     = -2115,              //  该侠客行副本只可打一次
    LVLMIS_PREMIS                   = -2116,              //  该侠客行副本需求前置任务未完成

    NO_ROOM_INFOS                   = -2130,              //  没有房间例表信息
    NOT_IN_ROOM                     = -2131,              //  不在房间内
    NO_TARGET_ROOM                  = -2132,              //  没有该房间
    ROOM_PLYS_MAX                   = -2133,              //  房间人数已满
    ROOM_PASSWD_ERR                 = -2134,              //  房间密码错误
    MUST_ROOM_OWNER                 = -2135,              //  不是房主
    IN_ROOM_ALREADY                 = -2136,              //  已进入了房间
    COMBPT_NEED                     = -2138,              // 战斗力不足

    NOT_USE_FRO_CLAN   				= -2150,    		  // 非帮派使用物品
    CLAN_ITEM_REQUIRE   			= -2151,    		  //  帮派消耗物品不够
    ITEM_BUY_CNT_LIM   				= -2152,    		  //   物品每日购买次数用完了
    DONATE_CNT_NOT_ENOUGH           = -2153,              //  捐献次数不足
    NOT_ENOUGH_DONATE               = -2154,              //  帮派贡献不足
    NOT_DIS_MIS_CLAN                = -2159,              //   工会未解散
    LOTTERY_TM_NOT_ACT  			= -2160,    		  //   不在抽奖有效时间
    

	HAS_MONTH_INVEST = -2168 ,   //已经进行过月投资
    NO_MONTH_INVEST = -2161 ,   //没有进行过月投资
    NO_MONTH_INVEST_AWARD = -2262 ,   //没有月投资回馈可领
    NO_MONTH_INVEST_ADD_AWARD = -2263 ,   //没有月投资累积回馈可领
    HAS_GET_ADD_AWARD = -2164 ,   //已经领取月投资累积回馈
    NO_LVLUP_INVEST = -2165, //没有进行过升级投资
    NO_LVLUP_INVEST_AWARD = -2266 ,   //没有升级投资回馈可领
    NO_ENOUGH_LEVEL = -2167,//等级不足不可领取
	
    STONE_CHANGE_ATT_LIMIT          = -2170,              //   非同类型同等级的宝石，不可转换

    NOT_WING_STREN_CONF          	= -2180,              //   未配置该等级配置
    WING_QUAL_HAS_LVL          		= -2181,              //   已经升级过该等级
    WING_QUAL_LVLUP_LASTLVL         = -2182,              //   未升级上一等级
    WING_ACT_NOT_ACT_THIS_SKILL     = -2183,              //   该技能未激活
    WING_ACT_NOT_ACT_THIS_HOLE      = -2184,              //   该技能栏位未激活
    WING_ACT_NOT_ACT_LAST_HOLE      = -2185,              //   上一技能栏位未激活
    WING_CANT_ACT_THIS_HOLE     	= -2186,              //   不能激活该技能栏位
    WING_ACT_HAD_ACT_THIS_HOLE     	= -2187,              //   已经激活该技能栏位
    WING_ACT_PRELVL_UNREACH     	= -2188,              //   前置条件未达成
    WING_ACT_HAS_SEL_SKIL           = -2189,              //   已设置该技能
    ENTER_LVL_UNREACH               = -2190,              //   进入副本条件不满足
    ENTER_MAP_UNREACH               = -2191,              //   未达到进入该地图条件
   	ENTER_LVL_COST_CONF_ERR         = -2192,              //  没有选择消耗配置
   	ENTER_LVL_COST_TP_ERR         	= -2193,              //   没有对应选择消耗配置类型

    RED_PAPER_TOTAL_LOW_CNT         = -2200,              //   发放的元宝数量小于元宝份数
    RED_PAPER_TOTAL_YB_LOW_MIN      = -2201,              //   总金额小于定义的最小金额
    RED_PAPER_TOTAL_YB_UP_MAX       = -2202,              //   总金额大于定义的最大金额
    RED_PAPER_CNT_LOW_MIN           = -2203,              //   红包份数太少了
    RED_PAPER_CNT_UP_MAX            = -2204,              //   红包份数超过上限了
    RED_PAPER_NOT_EXIST             = -2205,              //   红包不存在
    RED_PAPER_EXPIRED               = -2206,              //   红包已过期
    RED_PAPER_HAD_FETCH             = -2207,              //   红包已经领完了
    PLY_HAD_FETCH_THIS_RED_PAPER    = -2208,              //   红包已领取
    NOT_EXIST_RECOVER_RED_PAPER     = -2209,              //   没有可回收的红包
    RED_PAPER_RAMDOM_ERROR          = -2210,              //   红包生成错误
    RED_PAPER_RESEND_CD             = -2211,              //   红包重新发放冷却中

    ITM_CANT_ADD_RAREATT            = -2220,              //    该道具不能用于增加稀有属性 
    EQP_REACH_MAX_RAREATT           = -2221,              //    该装备已到达卓越稀有条数限制
    EQP_CANT_ADD_RAREATT            = -2222,              //    该装备不能增加稀有属性
    EQP_NOT_EXATT                   = -2223,              //    必须是卓越装备才可增加
    EQP_NOT_RARE_ATT                = -2224,              //    不存在该稀有属性
    EQP_CANT_EXC_RARE_ATT           = -2225,              //    装备不可替换稀有属性
    NOT_SUCH_LOCK_RARE_ATT          = -2226,              //    需要锁定的稀有属性不存在
    EQP_CANT_CHANGE_MULT_RARE_ATT   = -2227,              //    装备不可洗练稀有属性


    EQP_LEVEL_NOT_ENOUGH            = -3100,              //    装备强化等级不够
    EQP_NOT_UPGRADEABLE             = -3101,              //    装备不能进阶，无进阶配置
    EQP_UPGRADE_PLAYER_LEVEL_LOW    = -3102,              //    玩家等级不足，装备无法进阶
    EQP_UPGRADE_PLAYER_TARGET_LEVEL_TOO_HIGH  =-3103,     //    玩家的等级不满足进阶后的装备的等级要求
    EQP_ITEM_COMPOSE_NUM_ERR        = -3104,              //    合成道具数量错误

    NOT_ENOUGH_MONEY                = -4000,              //    金钱不足
    PACKAGE_FULL                    = -4001,              //    背包已满
    PACKAGE_GRID_NOT_ENOUGH         = -4002,              //    背包空余格子数不够
    NOT_ENOUGH_YB                   = -4003,              //    元宝不足
    NOT_ENOUGH_ENERGY               = -4004,              //    体力不足

    ITEM_COMPOSE_ERR                = -4100,              //    道具合成出错
    ITEM_MAX_NUM                    = -4101,              //    超过道具最大堆叠
    ITEM_PRICE_ERROR                = -4102,              //    道具售价错误

    TOURNAMENT_MAX_TIMES            = -4200,              //    比武场次数过多


    PET_AlREADY_HAVE_SAME           = -5000,              //    已经拥有了该英雄了
    PET_NOT_EXIST                   = -5001,              //    你没有这个英雄
    PET_ALREADY_ON_LIST             = -5002,              //    该英雄已经出阵
    PET_LIST_NO_ERR                 = -5003,              //    英雄阵号错误
    PET_IS_DEAD                     = -5004,              //    英雄已死
    PET_NOT_ON_LIST                 = -5005,              //    英雄当前不在阵上
    PET_MAX_STRENGTHEN              = -5006,              //    英雄已达到最高强化等级
    PET_MAX_LEVEL                   = -5007,              //    英雄已达最高等级
    PET_NOT_REBORN                  = -5008,              //    英雄不可重生
    PET_PLAYER_LEVEL_NOT_ENOUGTH    = -5009,              //    角色等级不够，无法上阵英雄
    PET_SUMMON_CONFIG_ERR           = -5010,              //    英雄召唤配置错误
    PET_SUMMON_ITEM_NOT_ENOUGH      = -5011,              //    英雄残卷不足

    LEVEL_PRIZE_REWARDED            = -6000,              //    副本奖励已经领取过了
    LEVEL_PRIZE_UNAVAILABLE         = -6001,              //    无法领取副本奖励
    LEVEL_NOT_IN_LEVEL              = -6002,              //    不在副本内，或副本未找到
    LEVEL_NO_RECORD_FOUND           = -6003,              //    未通关该副本
    LEVEL_LEFT_TIMES_OUT            = -6004,              //    今日该副本次数已耗尽
    LEVEL_LEFT_RESET_TIMES_OUT      = -6005,              //    今日该副本重置次数已耗尽
    LEVEL_SCORE_NOT_ENOUGH          = -6006,              //    副本分数不够，无法扫荡

    SKILL_NOT_LEARNED               = -7000,              //    技能尚未学习
    SKILL_CONF_NOT_FOUND            = -7001,              //    技能配置不存在
    SKILL_MAX_LEVEL                 = -7002,              //    技能已达最高等级

    RANK_SYSTEM_NOT_EXIST           = -7100,              //    排行榜不存在

    LOTTERY_HELPCOIN_NOT_ENOUGH     = -7200,              //    助战令数量不够

    MYSTORY_TIME_NOT_ENOUGH         = -7501,              //    免费刷新时间未到
    MYSTORY_ITEM_NOT_EXIST          = -7502,              //    道具未刷新到
    MYSTORY_ITEM_SOLD_OUT           = -7503,              //    道具已经售罄
    MYSTORY_YB_REFRESH_MAX_TIMES    = -7504,              //    今日元宝刷新次数超限

    NOT_ENOUGH_NOBPT                = -7600,              //    荣誉点数不够
    
    ACHI_NOT_FOUND                  = -7800,              //    没有该成就
    ACHI_NOT_ACHIEVED               = -7801,              //    成就未完成
    ACHI_REWARDED                   = -7802,              //    成就奖励已领取
    ACHI_POINT_NOT_ENOUGH           = -7803,              //    成就点数不足

    TOURNAMENT_ENOUGH_CLG_TIMES     = -7900,              //    今天可挑战次数已满，无需购买
    TOURNAMENT_NOT_IN_OPP_LIST      = -7901,              //    对方不在挑战列表中
    TOURNAMENT_PLAYER_NOT_EXIST     = -7902,              //    玩家不存在
    TOURNAMENT_NO_REWARD            = -7903,              //    没有可以领取的比武场结算奖励
    TOURNAMENT_RANK_NO_REWARD       = -7904,              //    没有相应的比武场结算奖励配置
    TOURNAMENT_NO_SHOP_ITEM         = -7905,              //    荣誉商店中无此道具
    TOURNAMENT_NOT_ENOUGH_BUY_TIME  = -7906,              //    挑战购买次数已用完

    BUY_TILI_COUNT_NOT_ENOUGH       = -8000,             //    体力购买次数不足
    VIP_NOT_ACTIVATION              = -8001,             //     VIP未激活

    NAME_IS_TOO_LONG                = -8100,              // 名字过长
    NO_CHANGE_NAME                  = -8101,              //名字未改变
    EMPTY_MSG                       = -8102,              //消息不能为空
};
